In [ ]:
import numpy as np

def pl_para_padrao_simples(A, b, c, tipo, sinais, variaveis_livres=[]):

    # 1) Converter para minimização
    if tipo == 'max':
        c = -c
    
    # 2) Tratar variáveis livres: x_livre = x⁺ - x⁻
    for ind in sorted(variaveis_livres, reverse=True): #é necessário garantir fazer dos maiores indíces primeiros para ter certeza que esteja sendo feito a operação na variável certa
        coluna_negativa = -A[:, ind] 
        A = np.insert(A, ind + 1, coluna_negativa, axis=1) #inserimos na próxima coluna
        c = np.insert(c, ind + 1, -c[ind])
    
    # 3) Adicionar variáveis de folga/excesso
    n_restricoes = A.shape[0]
    
    for i in range(n_restricoes): #avaliar cada um dos sinais
        if sinais[i] == '<=': 
            nova_coluna = np.zeros(n_restricoes) 
            nova_coluna[i] = 1
            A = np.column_stack([A, nova_coluna])
            c = np.append(c, 0)
            
        elif sinais[i] == '>=':
            nova_coluna = np.zeros(n_restricoes)
            nova_coluna[i] = -1
            A = np.column_stack([A, nova_coluna])
            c = np.append(c, 0)
    
    return A, b, c

In [ ]:
# Montando o exemplo
# objetivo: max 3x1 + 2x2
# Restrição 1: x1 + x2 <= 4
# Restrição 2: x1 - x2 >= 2
A = np.array([
    [1, 1],
    [1, -1]
], dtype=float)

b = np.array([4, 2], dtype=float)

c = np.array([3, 2], dtype=float)  # função objetivo: 3x1 + 2x2

tipo = "max"  
sinais = ["<=", ">="]

variaveis_livres = [1]  # x2 é livre

# Chamando a função
A_padrao, b_padrao, c_padrao = pl_para_padrao_simples(A, b, c, tipo, sinais, variaveis_livres)

print("Matriz A (padrão):")
print(A_padrao)
print("\nVetor b (padrão):")
print(b_padrao)
print("\nVetor c (padrão):")
print(c_padrao)

Matriz A (padrão):
[[ 1.  1. -1.  1.  0.]
 [ 1. -1.  1.  0. -1.]]

Vetor b (padrão):
[4. 2.]

Vetor c (padrão):
[ 3.  2. -2.  0.  0.]
